# Generated by Django 5.2 on 2026-02-10 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('vendor_vat', models.CharField(blank=True, max_length=50)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('buyer_vat', models.CharField(blank=True, max_length=50)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('raw_ocr_response', models.JSONField(default=dict)),
                ('line_items', models.JSONField(default=list)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('field_confidences', models.JSONField(default=dict)),
                ('qr_code_data', models.JSONField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='invoices.invoice')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
