# Generated by Django 5.1 on 2026-02-08 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.FileField(upload_to='invoices/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(max_length=50)),
                ('image_hash', models.CharField(db_index=True, help_text='SHA-256 hash for duplicate detection', max_length=64)),
                ('invoice_type', models.CharField(choices=[('purchase', 'Purchase Invoice'), ('sales', 'Sales Invoice'), ('other', 'Other')], help_text='Required: classify as Purchase, Sales, or Other', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('ocr_processing', 'OCR Processing'), ('ocr_complete', 'OCR Complete'), ('verified', 'Verified'), ('posted', 'Posted to Odoo'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('ocr_data', models.JSONField(blank=True, help_text='OCR extracted data', null=True)),
                ('odoo_invoice_id', models.IntegerField(blank=True, help_text='Odoo invoice record ID', null=True)),
                ('zatca_status', models.CharField(blank=True, max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Uploaded'), ('tag_changed', 'Tag Changed'), ('status_changed', 'Status Changed'), ('ocr_processed', 'OCR Processed'), ('sent_to_odoo', 'Sent to Odoo'), ('zatca_verified', 'ZATCA Verified'), ('rejected', 'Rejected'), ('viewed', 'Viewed')], max_length=30)),
                ('details', models.JSONField(default=dict, help_text='Before/after state and extra info')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_in_status_cec546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type'], name='invoices_in_invoice_3d55b1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['image_hash'], name='invoices_in_image_h_b15444_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='invoices_in_created_09931a_idx'),
        ),
    ]
