# Generated by Django 5.2 on 2026-02-10 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_invoice_id', models.IntegerField(blank=True, null=True)),
                ('odoo_invoice_name', models.CharField(blank=True, max_length=100)),
                ('odoo_partner_id', models.IntegerField(blank=True, null=True)),
                ('invoice_type', models.CharField(choices=[('out_invoice', 'Customer Invoice'), ('in_invoice', 'Vendor Bill')], default='out_invoice', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('synced_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odoo_syncs', to='invoices.invoice')),
                ('synced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Odoo Sync Log',
                'verbose_name_plural': 'Odoo Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
